system: ./LiCoO2_mp-22526_conventional_standard.cif
mace_model: ../MACE-matpes-r2scan-omat-ft.model
optimizer:
  type: FIRE2
  fmax: 0.05
  max steps: 5000
output files:
  thermo: VP/thermo.csv
  trajectory: VP/trj.xyz
  convex hull: VP/hull.csv
  voltage: VP/voltage.csv
states folder: VP/states
working ion:
  charge carried: 1
  chemical potential:
    Li: -2.3642802960570437
continue: false
removal_method: semi_brute_force
plots: true
plots folder: plots
voltage_max: null
voltage_min: null
steps_id: null
post_process: false
finish_interrupted_step: false
fully_intercalated: false
fully_deintercalated: false
plot_frequency: 1
