continue: false
removal_method: brute_force
system: ./2x1x1-LiFePO4.cif
mace_model: ../MACE-matpes-r2scan-omat-ft.model
optimizer:
  type: FIRE2
  fmax: 0.05
  max steps: 5000
output files:
  thermo: VP/thermo.csv
  trajectory: VP/trj.xyz
  convex hull: VP/hull.csv
  voltage: VP/voltage.csv
states folder: VP/states
working ion:
  charge carried: 1
  chemical potential:
    Li: -2.364280296057041
steps_id: null
post_process: false
finish_interrupted_step: false
